####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode
#
# Before building the container image run:
#
# ./mvnw package -Pnative
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.native -t quarkus/hibernate-orm .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/hibernate-orm
#
###
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.10-1791395196@sha256:2ea767876991dd9c213986be20e8d6352b9c27e310a4102a5150081daac176d2
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/*-runner /work/application

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]