name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.5
        env:
          POSTGRES_USER: quarkus_test
          POSTGRES_PASSWORD: quarkus_test
          POSTGRES_DB: quarkus_test
        ports:
          - 127.0.0.1:5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Grant execute permission for mvnw
      run: chmod +x mvnw
    - name: Build with Maven
      run: ./mvnw -B package --file pom.xml
    - name: Upload reports
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: reports
        path: |
          build/reports
          target/surefire-reports
